# workmux configuration for spandaworks
# Integrated consciousness-aware productivity system

panes:
  - command: <agent>
    focus: true

# Spandaworks is a monorepo with Python packages
# No node_modules or heavy build artifacts to symlink

files:
  symlink: []
  copy: []
