# workmux configuration for spanda-works
# Integrated consciousness-aware productivity system

panes:
  - command: <agent>
    focus: true

# Spanda Works is a monorepo with Python packages
# No node_modules or heavy build artifacts to symlink

files:
  symlink: []
  copy: []
